service: user-service

plugins:
  - serverless-offline
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1

functions:
  healthcheck:
    handler: src/main.healthcheck
    events:
      - http:
          path: health
          method: GET
